import fs from 'fs';
import path from 'path';

// Use process.cwd() to resolve paths relative to the project root
const ROOT_DIR = process.cwd();
const GAMES_DIR = path.join(ROOT_DIR, 'public', 'games');
// FIX: Output to src/data instead of root/data
const OUTPUT_FILE = path.join(ROOT_DIR, 'src', 'data', 'scannedGames.ts');

console.log('\n🔍 Starting Game Scan...');
console.log('📂 Source:', GAMES_DIR);

// Ensure directory exists
if (!fs.existsSync(GAMES_DIR)) {
  console.warn(`⚠️  Directory ${GAMES_DIR} not found. Creating it...`);
  fs.mkdirSync(GAMES_DIR, { recursive: true });
}

// Read folders
const items = fs.existsSync(GAMES_DIR) ? fs.readdirSync(GAMES_DIR, { withFileTypes: true }) : [];

let successCount = 0;
let failCount = 0;

const games = items
  .filter(item => item.isDirectory())
  .map(dir => {
    const folderName = dir.name;
    const gamePath = path.join(GAMES_DIR, folderName);
    
    // Check if index.html exists (to confirm it is a game)
    if (!fs.existsSync(path.join(gamePath, 'index.html'))) {
        console.warn(`❌ [FAILED] Folder '${folderName}' skipped: Missing 'index.html'`);
        failCount++;
        return null;
    }

    // Check for thumbnail
    const hasThumb = fs.existsSync(path.join(gamePath, 'thumbnail.png'));
    const thumbnail = hasThumb ? `games/${folderName}/thumbnail.png` : null;
    
    if (!hasThumb) {
        console.warn(`⚠️  [WARNING] Folder '${folderName}': Missing 'thumbnail.png' (Using placeholder)`);
    }

    // Check for info.json metadata
    let info = {};
    const infoPath = path.join(gamePath, 'info.json');
    if (fs.existsSync(infoPath)) {
        try {
            info = JSON.parse(fs.readFileSync(infoPath, 'utf-8'));
        } catch (e) {
            console.error(`❌ [ERROR] Folder '${folderName}': Corrupt 'info.json' - ${e.message}`);
        }
    }

    // Format Name: "super-mario" -> "Super Mario" (fallback if no name in info.json)
    const formattedName = folderName
      .replace(/-/g, ' ')
      .replace(/_/g, ' ')
      .replace(/\b\w/g, l => l.toUpperCase());

    successCount++;
    return {
      id: folderName,
      name: info.name || formattedName,
      slug: folderName,
      folder: `games/${folderName}`,
      thumbnail: thumbnail,
      description: info.description || null,
      category: info.category || null,
      rating: info.rating || null
    };
  })
  .filter(Boolean); // Remove nulls

// Ensure output directory exists
const outputDir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// Generate TypeScript content
const fileContent = `// This file is auto-generated by scripts/scan-games.js
export interface ScannedGame {
  id: string;
  name: string;
  slug: string;
  folder: string;
  thumbnail: string | null;
  description: string | null;
  category: string | null;
  rating: number | null;
}

export const scannedGames: ScannedGame[] = ${JSON.stringify(games, null, 2)};
`;

// Write to TS file
fs.writeFileSync(OUTPUT_FILE, fileContent);

console.log(`\n--------------------------------------------------`);
console.log(`✅ Scan Complete!`);
console.log(`📥 Loaded Games: ${successCount}`);
console.log(`🚫 Failed Folders: ${failCount}`);
console.log(`📁 Data written to: src/data/scannedGames.ts`);
console.log(`--------------------------------------------------\n`);