"""Theme tokens for ATAssistant GUI."""

# ─── Window ──────────────────────────────────────────
WINDOW_TITLE = "AT Assistant"
WINDOW_WIDTH = 580
WINDOW_HEIGHT = 750
MIN_WIDTH = 420
MIN_HEIGHT = 500

DARK_THEME = {
    "BG_PRIMARY": "#11101a",
    "BG_SECONDARY": "#171420",
    "BG_INPUT": "#211d2b",
    "BG_BUBBLE_USER": "#ff5a3d",
    "BG_BUBBLE_BOT": "#171420",
    "BG_BUBBLE_ERROR": "#35101f",
    "FG_PRIMARY": "#fffaf7",
    "FG_SECONDARY": "#c8c1d9",
    "FG_USER": "#ffffff",
    "FG_BOT": "#fffaf7",
    "FG_ERROR": "#ff6b8a",
    "FG_SUCCESS": "#5ee0a5",
    "FG_PLACEHOLDER": "#8d879b",
    "ACCENT": "#ff5a3d",
    "ACCENT_HOVER": "#d9432a",
    "ACCENT_CONFIRM": "#0f8b5f",
    "ACCENT_CONFIRM_HOVER": "#10a875",
    "ACCENT_CANCEL": "#e11d48",
    "ACCENT_CANCEL_HOVER": "#fb315e",
    "ACCENT_CHOICE": "#2a2433",
    "ACCENT_CHOICE_HOVER": "#373044",
    "BORDER_COLOR": "#2d2738",
    "SCROLLBAR_COLOR": "#40384d",
    "SCROLLBAR_HOVER": "#5a5069",
    "MIC_OFF_COLOR": "#7c3aed",
    "MIC_OFF_HOVER": "#6025d1",
    "MIC_ON_COLOR": "#ff5a3d",
    "MIC_ON_HOVER": "#d9432a",
}

LIGHT_THEME = {
    "BG_PRIMARY": "#f7f8ff",
    "BG_SECONDARY": "#ffffff",
    "BG_INPUT": "#edf1f8",
    "BG_BUBBLE_USER": "#fff2ed",
    "BG_BUBBLE_BOT": "#ffffff",
    "BG_BUBBLE_ERROR": "#fff0f4",
    "FG_PRIMARY": "#151321",
    "FG_SECONDARY": "#667085",
    "FG_USER": "#151321",
    "FG_BOT": "#151321",
    "FG_ERROR": "#e11d48",
    "FG_SUCCESS": "#0f8b5f",
    "FG_PLACEHOLDER": "#98a2b3",
    "ACCENT": "#ff5a3d",
    "ACCENT_HOVER": "#d9432a",
    "ACCENT_CONFIRM": "#0f8b5f",
    "ACCENT_CONFIRM_HOVER": "#10a875",
    "ACCENT_CANCEL": "#e11d48",
    "ACCENT_CANCEL_HOVER": "#fb315e",
    "ACCENT_CHOICE": "#edf1f8",
    "ACCENT_CHOICE_HOVER": "#dfe6f1",
    "BORDER_COLOR": "#dde3f0",
    "SCROLLBAR_COLOR": "#dfe6f1",
    "SCROLLBAR_HOVER": "#c4cadd",
    "MIC_OFF_COLOR": "#7c3aed",
    "MIC_OFF_HOVER": "#6025d1",
    "MIC_ON_COLOR": "#ff5a3d",
    "MIC_ON_HOVER": "#d9432a",
}


def get_theme_palette(mode: str = "dark") -> dict[str, str]:
    return DARK_THEME if (mode or "").lower() == "dark" else LIGHT_THEME


_DEFAULT = get_theme_palette("dark")

BG_PRIMARY = _DEFAULT["BG_PRIMARY"]
BG_SECONDARY = _DEFAULT["BG_SECONDARY"]
BG_INPUT = _DEFAULT["BG_INPUT"]
BG_BUBBLE_USER = _DEFAULT["BG_BUBBLE_USER"]
BG_BUBBLE_BOT = _DEFAULT["BG_BUBBLE_BOT"]
BG_BUBBLE_ERROR = _DEFAULT["BG_BUBBLE_ERROR"]
FG_PRIMARY = _DEFAULT["FG_PRIMARY"]
FG_SECONDARY = _DEFAULT["FG_SECONDARY"]
FG_USER = _DEFAULT["FG_USER"]
FG_BOT = _DEFAULT["FG_BOT"]
FG_ERROR = _DEFAULT["FG_ERROR"]
FG_SUCCESS = _DEFAULT["FG_SUCCESS"]
FG_PLACEHOLDER = _DEFAULT["FG_PLACEHOLDER"]
ACCENT = _DEFAULT["ACCENT"]
ACCENT_HOVER = _DEFAULT["ACCENT_HOVER"]
ACCENT_CONFIRM = _DEFAULT["ACCENT_CONFIRM"]
ACCENT_CONFIRM_HOVER = _DEFAULT["ACCENT_CONFIRM_HOVER"]
ACCENT_CANCEL = _DEFAULT["ACCENT_CANCEL"]
ACCENT_CANCEL_HOVER = _DEFAULT["ACCENT_CANCEL_HOVER"]
ACCENT_CHOICE = _DEFAULT["ACCENT_CHOICE"]
ACCENT_CHOICE_HOVER = _DEFAULT["ACCENT_CHOICE_HOVER"]
BORDER_COLOR = _DEFAULT["BORDER_COLOR"]
SCROLLBAR_COLOR = _DEFAULT["SCROLLBAR_COLOR"]
SCROLLBAR_HOVER = _DEFAULT["SCROLLBAR_HOVER"]

# ─── Fonts ───────────────────────────────────────────
FONT_FAMILY = "Segoe UI"
FONT_SIZE_NORMAL = 12
FONT_SIZE_SMALL = 10
FONT_SIZE_TITLE = 15
FONT_SIZE_LABEL = 12

# ─── Sizing ──────────────────────────────────────────
BUBBLE_PADX = 16
BUBBLE_PADY = 10
BUBBLE_RADIUS = 14
INPUT_HEIGHT = 44
BUTTON_HEIGHT = 38
ACTION_BAR_HEIGHT = 54
CHAT_PADX = 12
CHAT_PADY = 8
