// This file is auto-generated by scripts/scan-games.js
export interface ScannedGame {
  id: string;
  name: string;
  slug: string;
  folder: string;
  thumbnail: string | null;
  description: string | null;
  category: string | null;
  rating: number | null;
}

export const scannedGames: ScannedGame[] = [
  {
    "id": "2048 Master",
    "name": "2048 Master",
    "slug": "2048 Master",
    "folder": "games/2048 Master",
    "thumbnail": "games/2048 Master/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "3D Roulette Casino Game",
    "name": "3D Roulette Casino Game",
    "slug": "3D Roulette Casino Game",
    "folder": "games/3D Roulette Casino Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "3D-Hartwig-chess-set-master",
    "name": "3D Hartwig Chess Set Master",
    "slug": "3D-Hartwig-chess-set-master",
    "folder": "games/3D-Hartwig-chess-set-master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Action Platformer",
    "name": "Action Platformer",
    "slug": "Action Platformer",
    "folder": "games/Action Platformer",
    "thumbnail": "games/Action Platformer/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Alien Way",
    "name": "Alien Way",
    "slug": "Alien Way",
    "folder": "games/Alien Way",
    "thumbnail": "games/Alien Way/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Archer Hero",
    "name": "Archer Hero",
    "slug": "Archer Hero",
    "folder": "games/Archer Hero",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Arnie Attack",
    "name": "Arnie Attack",
    "slug": "Arnie Attack",
    "folder": "games/Arnie Attack",
    "thumbnail": "games/Arnie Attack/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Astray Master",
    "name": "Astray Master",
    "slug": "Astray Master",
    "folder": "games/Astray Master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Astray-master",
    "name": "Astray Master",
    "slug": "Astray-master",
    "folder": "games/Astray-master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Auto Platformer Mobile",
    "name": "Auto Platformer Mobile",
    "slug": "Auto Platformer Mobile",
    "folder": "games/Auto Platformer Mobile",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Bingo Gambling Game",
    "name": "Bingo Gambling Game",
    "slug": "Bingo Gambling Game",
    "folder": "games/Bingo Gambling Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "breaklock-main",
    "name": "Breaklock Main",
    "slug": "breaklock-main",
    "folder": "games/breaklock-main",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "City Hero",
    "name": "City Hero",
    "slug": "City Hero",
    "folder": "games/City Hero",
    "thumbnail": "games/City Hero/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Classic Bowling Sport Game",
    "name": "Classic Bowling Sport Game",
    "slug": "Classic Bowling Sport Game",
    "folder": "games/Classic Bowling Sport Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Clumsy Bird Master",
    "name": "Clumsy Bird Master",
    "slug": "Clumsy Bird Master",
    "folder": "games/Clumsy Bird Master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Coloring Book",
    "name": "Coloring Book",
    "slug": "Coloring Book",
    "folder": "games/Coloring Book",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Crazy Parking",
    "name": "Crazy Parking",
    "slug": "Crazy Parking",
    "folder": "games/Crazy Parking",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Crocofinity",
    "name": "Crocofinity",
    "slug": "Crocofinity",
    "folder": "games/Crocofinity",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Danger Cliffs",
    "name": "Danger Cliffs",
    "slug": "Danger Cliffs",
    "folder": "games/Danger Cliffs",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Destiny Of Warrior",
    "name": "Destiny Of Warrior",
    "slug": "Destiny Of Warrior",
    "folder": "games/Destiny Of Warrior",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Dice Game",
    "name": "Dice Game",
    "slug": "Dice Game",
    "folder": "games/Dice Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Dribble Kings Football Game",
    "name": "Dribble Kings Football Game",
    "slug": "Dribble Kings Football Game",
    "folder": "games/Dribble Kings Football Game",
    "thumbnail": "games/Dribble Kings Football Game/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Duck Shooter",
    "name": "Duck Shooter",
    "slug": "Duck Shooter",
    "folder": "games/Duck Shooter",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Electrio Logic Game",
    "name": "Electrio Logic Game",
    "slug": "Electrio Logic Game",
    "folder": "games/Electrio Logic Game",
    "thumbnail": "games/Electrio Logic Game/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Fantasy Forest Mobile Game",
    "name": "Fantasy Forest Mobile Game",
    "slug": "Fantasy Forest Mobile Game",
    "folder": "games/Fantasy Forest Mobile Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Fishing Frenzy Mobile",
    "name": "Fishing Frenzy Mobile",
    "slug": "Fishing Frenzy Mobile",
    "folder": "games/Fishing Frenzy Mobile",
    "thumbnail": "games/Fishing Frenzy Mobile/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "flexboxfroggy-main",
    "name": "Flexboxfroggy Main",
    "slug": "flexboxfroggy-main",
    "folder": "games/flexboxfroggy-main",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Flight Sim",
    "name": "Flight Sim",
    "slug": "Flight Sim",
    "folder": "games/Flight Sim",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Flip Card Memory Test",
    "name": "Flip Card Memory Test",
    "slug": "Flip Card Memory Test",
    "folder": "games/Flip Card Memory Test",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Formula Drag",
    "name": "Formula Drag",
    "slug": "Formula Drag",
    "folder": "games/Formula Drag",
    "thumbnail": "games/Formula Drag/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Four Colors Card Game",
    "name": "Four Colors Card Game",
    "slug": "Four Colors Card Game",
    "folder": "games/Four Colors Card Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Frogtastic",
    "name": "Frogtastic",
    "slug": "Frogtastic",
    "folder": "games/Frogtastic",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Grave Drive",
    "name": "Grave Drive",
    "slug": "Grave Drive",
    "folder": "games/Grave Drive",
    "thumbnail": "games/Grave Drive/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Green Chick Jump",
    "name": "Green Chick Jump",
    "slug": "Green Chick Jump",
    "folder": "games/Green Chick Jump",
    "thumbnail": "games/Green Chick Jump/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "gridgarden-master",
    "name": "Gridgarden Master",
    "slug": "gridgarden-master",
    "folder": "games/gridgarden-master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "HexGL-master",
    "name": "HexGL Master",
    "slug": "HexGL-master",
    "folder": "games/HexGL-master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Hextris",
    "name": "Hextris",
    "slug": "Hextris",
    "folder": "games/Hextris",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "hextris-gh-pages",
    "name": "Hextris Gh Pages",
    "slug": "hextris-gh-pages",
    "folder": "games/hextris-gh-pages",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Hold Position",
    "name": "Hold Position",
    "slug": "Hold Position",
    "folder": "games/Hold Position",
    "thumbnail": "games/Hold Position/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Jelly Break Match 3 Game",
    "name": "Jelly Break Match 3 Game",
    "slug": "Jelly Break Match 3 Game",
    "folder": "games/Jelly Break Match 3 Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Jet Halloween",
    "name": "Jet Halloween",
    "slug": "Jet Halloween",
    "folder": "games/Jet Halloween",
    "thumbnail": "games/Jet Halloween/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Jump Ninja Hero",
    "name": "Jump Ninja Hero",
    "slug": "Jump Ninja Hero",
    "folder": "games/Jump Ninja Hero",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Koby Jump Escape",
    "name": "Koby Jump Escape",
    "slug": "Koby Jump Escape",
    "folder": "games/Koby Jump Escape",
    "thumbnail": "games/Koby Jump Escape/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "last-colony-master",
    "name": "Last Colony Master",
    "slug": "last-colony-master",
    "folder": "games/last-colony-master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Lottery Numbers",
    "name": "Lottery Numbers",
    "slug": "Lottery Numbers",
    "folder": "games/Lottery Numbers",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Ludo Multiplayer",
    "name": "Ludo Multiplayer",
    "slug": "Ludo Multiplayer",
    "folder": "games/Ludo Multiplayer",
    "thumbnail": "games/Ludo Multiplayer/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Moto Beach Ride",
    "name": "Moto Beach Ride",
    "slug": "Moto Beach Ride",
    "folder": "games/Moto Beach Ride",
    "thumbnail": "games/Moto Beach Ride/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Night Dress",
    "name": "Night Dress",
    "slug": "Night Dress",
    "folder": "games/Night Dress",
    "thumbnail": "games/Night Dress/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Ninja Run Mobile Game",
    "name": "Ninja Run Mobile Game",
    "slug": "Ninja Run Mobile Game",
    "folder": "games/Ninja Run Mobile Game",
    "thumbnail": "games/Ninja Run Mobile Game/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Ohh1 Master",
    "name": "Ohh1 Master",
    "slug": "Ohh1 Master",
    "folder": "games/Ohh1 Master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Open Restaurant Game",
    "name": "Open Restaurant Game",
    "slug": "Open Restaurant Game",
    "folder": "games/Open Restaurant Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Pacman Canvas Master",
    "name": "Pacman Canvas Master",
    "slug": "Pacman Canvas Master",
    "folder": "games/Pacman Canvas Master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Penalty Kicks Sport Game",
    "name": "Penalty Kicks Sport Game",
    "slug": "Penalty Kicks Sport Game",
    "folder": "games/Penalty Kicks Sport Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Pocket-Island",
    "name": "Pocket Island",
    "slug": "Pocket-Island",
    "folder": "games/Pocket-Island",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Poker Jacks Or Better Casino Game",
    "name": "Poker Jacks Or Better Casino Game",
    "slug": "Poker Jacks Or Better Casino Game",
    "folder": "games/Poker Jacks Or Better Casino Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Quiz Game",
    "name": "Quiz Game",
    "slug": "Quiz Game",
    "folder": "games/Quiz Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Racer Master",
    "name": "Racer Master",
    "slug": "Racer Master",
    "folder": "games/Racer Master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Rob Runner",
    "name": "Rob Runner",
    "slug": "Rob Runner",
    "folder": "games/Rob Runner",
    "thumbnail": "games/Rob Runner/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Run Into Death Shooter Game",
    "name": "Run Into Death Shooter Game",
    "slug": "Run Into Death Shooter Game",
    "folder": "games/Run Into Death Shooter Game",
    "thumbnail": "games/Run Into Death Shooter Game/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Sheepop Mobile Game",
    "name": "Sheepop Mobile Game",
    "slug": "Sheepop Mobile Game",
    "folder": "games/Sheepop Mobile Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Sidechain Mobile",
    "name": "Sidechain Mobile",
    "slug": "Sidechain Mobile",
    "folder": "games/Sidechain Mobile",
    "thumbnail": "games/Sidechain Mobile/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Slot Machine Fruits Casino Game",
    "name": "Slot Machine Fruits Casino Game",
    "slug": "Slot Machine Fruits Casino Game",
    "folder": "games/Slot Machine Fruits Casino Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Slot Ramses Casino Game",
    "name": "Slot Ramses Casino Game",
    "slug": "Slot Ramses Casino Game",
    "folder": "games/Slot Ramses Casino Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Soldier Way",
    "name": "Soldier Way",
    "slug": "Soldier Way",
    "folder": "games/Soldier Way",
    "thumbnail": "games/Soldier Way/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "SpaceInvaders-master",
    "name": "SpaceInvaders Master",
    "slug": "SpaceInvaders-master",
    "folder": "games/SpaceInvaders-master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Spin The Wheel",
    "name": "Spin The Wheel",
    "slug": "Spin The Wheel",
    "folder": "games/Spin The Wheel",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Spot The Differences Game",
    "name": "Spot The Differences Game",
    "slug": "Spot The Differences Game",
    "folder": "games/Spot The Differences Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Super 8 Race",
    "name": "Super 8 Race",
    "slug": "Super 8 Race",
    "folder": "games/Super 8 Race",
    "thumbnail": "games/Super 8 Race/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Super Greens",
    "name": "Super Greens",
    "slug": "Super Greens",
    "folder": "games/Super Greens",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Sweet World Game",
    "name": "Sweet World Game",
    "slug": "Sweet World Game",
    "folder": "games/Sweet World Game",
    "thumbnail": "games/Sweet World Game/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Tank Wars Premium",
    "name": "Tank Wars Premium",
    "slug": "Tank Wars Premium",
    "folder": "games/Tank Wars Premium",
    "thumbnail": "games/Tank Wars Premium/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Tap Supermarket",
    "name": "Tap Supermarket",
    "slug": "Tap Supermarket",
    "folder": "games/Tap Supermarket",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "The Sorcerer Game",
    "name": "The Sorcerer Game",
    "slug": "The Sorcerer Game",
    "folder": "games/The Sorcerer Game",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "tower_game-master",
    "name": "Tower Game Master",
    "slug": "tower_game-master",
    "folder": "games/tower_game-master",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Tricky Crab",
    "name": "Tricky Crab",
    "slug": "Tricky Crab",
    "folder": "games/Tricky Crab",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Trzpopit",
    "name": "Trzpopit",
    "slug": "Trzpopit",
    "folder": "games/Trzpopit",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Viking Way",
    "name": "Viking Way",
    "slug": "Viking Way",
    "folder": "games/Viking Way",
    "thumbnail": "games/Viking Way/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Volleymal Sport Games",
    "name": "Volleymal Sport Games",
    "slug": "Volleymal Sport Games",
    "folder": "games/Volleymal Sport Games",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Wrecked",
    "name": "Wrecked",
    "slug": "Wrecked",
    "folder": "games/Wrecked",
    "thumbnail": "games/Wrecked/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Zombie Shooter 2D Isometric Action",
    "name": "Zombie Shooter 2D Isometric Action",
    "slug": "Zombie Shooter 2D Isometric Action",
    "folder": "games/Zombie Shooter 2D Isometric Action",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Zombie Shooter Mobile",
    "name": "Zombie Shooter Mobile",
    "slug": "Zombie Shooter Mobile",
    "folder": "games/Zombie Shooter Mobile",
    "thumbnail": "games/Zombie Shooter Mobile/thumbnail.png",
    "description": null,
    "category": null,
    "rating": null
  },
  {
    "id": "Zombies Night",
    "name": "Zombies Night",
    "slug": "Zombies Night",
    "folder": "games/Zombies Night",
    "thumbnail": null,
    "description": null,
    "category": null,
    "rating": null
  }
];
